services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

  redis:
    logging:
      driver: none
    image: redis
    restart: always
    command: redis-server
    ports:
      - 6379:6379

  realistikgdps:
    image: realistikgdps:latest
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis
    restart: always
    environment:
      - HTTP_PORT=80
      - SQL_PASS=root
