services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rgdps
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

  redis:
    logging:
      driver: none
    image: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"

  realistikgdps:
    image: realistikgdps:latest
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis
      - meilisearch
    restart: always
    environment:
      - HTTP_PORT=80
      - HTTP_HOST=0.0.0.0
      - HTTP_URL_PREFIX=/gdpsdatabased
      - SQL_USER=root
      - SQL_PASS=root
      - SQL_HOST=mysql
      - SQL_DB=rgdps
      - SQL_PORT=3306
      - REDIS_HOST=redis
      - DATA_LEVELS=/data/levels
      - DATA_SAVES=/data/saves
      - MEILI_HOST=meilisearch
      - MEILI_PORT=7700
      - MEILI_KEY=masterKey
    volumes:
      - ./data/levels:/data/levels
      - ./data/saves:/data/saves
      # Migrations
      - ./database/migrations:/app/database/migrations

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    ports:
      - "7700:7700"
    volumes:
      - ./meilisearch:/data.ms
    environment:
      - MEILI_MASTER_KEY=masterKey
