apiVersion: apps/v1
kind: Deployment
metadata:
  name: realistikgdps-deployment
spec:
  selector:
    matchLabels:
      app: realistikgdps
  template:
    metadata:
      labels:
        app: realistikgdps
    spec:
      containers:
      - name: realistikgdps
        image: realistikgdps:latest
        ports:
        - containerPort: 80
        env:
          - name: KUBERNETES
            value: "1"
          - name: HTTP_PORT
            value: $(HTTP_PORT)
          - name: HTTP_HOST
            value: $(HTTP_HOST)
          - name: HTTP_URL_PREFIX
            value: $(HTTP_URL_PREFIX)
          - name: SQL_USER
            value: $(SQL_USER)
          - name: SQL_PASS
            value: $(SQL_PASS)
          - name: SQL_HOST
            value: $(SQL_HOST)
          - name: SQL_DB
            value: $(SQL_DB)
          - name: SQL_PORT
            value: $(SQL_PORT)
          - name: REDIS_HOST
            value: $(REDIS_HOST)
          - name: REDIS_PORT
            value: $(REDIS_PORT)
          - name: REDIS_DB
            value: $(REDIS_DB)
          - name: MEILI_HOST
            value: $(MEILI_HOST)
          - name: MEILI_PORT
            value: $(MEILI_PORT)
          - name: MEILI_KEY
            value: $(MEILI_KEY)
          - name: SERVICE_READINESS_TIMEOUT
            value: $(SERVICE_READINESS_TIMEOUT)
          - name: SRV_NAME
            value: $(SRV_NAME)
          - name: S3_ENABLED
            value: $(S3_ENABLED)
          - name: S3_BUCKET
            value: $(S3_BUCKET)
          - name: S3_REGION
            value: $(S3_REGION)
          - name: S3_ENDPOINT
            value: $(S3_ENDPOINT)
          - name: S3_ACCESS_KEY
            value: $(S3_ACCESS_KEY)
          - name: S3_SECRET_KEY
            value: $(S3_SECRET_KEY)
          - name: LOCAL_ROOT
            value: /data
          - name: APP_COMPONENT
            value: $(APP_COMPONENT)
